### ISSUE TITLE
onNodeSelect is not invoked when selection is from selected -> halfSelected

### ISSUE THREAD

**Issue by douglasjohnson** [dgreene1/react-accessible-treeview#119]
**Describe the bug**
The onNodeSelect callback should be invoked in the scenario where an already selected node is selected to go from a selected -> halfSelected state.

**Code That Causes The Issue**
See failing unit test in PR https://github.com/dgreene1/react-accessible-treeview/pull/118

Test in TestViewOnNodeSelect.test.tsx - "onNodeSelect should be called when node is deselected to a half-selected state"

**To Reproduce**
See failing unit test in PR

**Expected behavior**
See failing unit test in PR

**Additional context**
The use case here is when the selectedIds are controlled with custom logic determining the propagation, therefore the propagate props are disabled. In this scenario the lack of callback to onNodeSelect prevents the consumer from being notified of the interaction with the node.

**Comment by douglasjohnson** [comment]
@kpustakhod I'd be keen on your view on this? I've added the failing test based on what I would expect. I can attempt to address the issue in the same PR.

**Comment by kpustakhod** [comment]
@douglasjohnson should be addressed in https://github.com/dgreene1/react-accessible-treeview/pull/121

**Comment by dgreene1** [comment]
Resolved in #121

**Comment by dgreene1** [comment]
My apologies, I didn't realize that #121 was not merged yet. Reopening this issue.
