### ISSUE TITLE
Don't call onExpand for initial expandedIds

### ISSUE THREAD

**Issue by brettinternet** [dgreene1/react-accessible-treeview#128]
**Describe the bug**
There are some issues with using controlled state for expanded IDs. Consider this example where expanded state is controlled in the parent component (a practical example would be where state is persisted in local/session storage).

**Code That Causes The Issue**
```ts
const data = flattenTree({
  name: '',
  children: names,
})
const parentIds = useMemo(
  () =>
    data.reduce<NodeId[]>(
      (acc, node) => (node.children.length ? acc.concat(node.id) : acc),
      []
    ),
  [data]
)
const [expandedIds, setExpandedIds] = useSessionStorage(storageKey, parentIds)

<TreeView
  data={data}
  onExpand={({ element: { id }, isExpanded }) => {
    setExpandedIds((ids) =>
      produce(ids, (draft) => {
        if (!isExpanded) {
          remove(draft, (nodeId) => nodeId === id)
        } else {
          draft.push(id)
        }
      })
    )
  }}
  expandedIds={expandedIds}
  onNodeSelect={({ element }) => {
    // ...handle
  }}
  nodeRenderer={(props) => (
    <NodeRenderer {...props} itemProps={nodePropsMap[props.element.name]} />
  )}
  clickAction="EXCLUSIVE_SELECT"
  aria-label="Navigation"
  expandOnKeyboardSelect
/>
```

The values passed into `expandedIds` cause `onExpand` to be called on the initial render. This also causes the list items to be focused on the initial page load which is an accessibility issue.

**To Reproduce**
Use parent state to control the expanded IDs.

**Expected behavior**
Like with form inputs, I'd expect that controlled state to accept an initial value, and subsequent changes to the state from user input to call a callback, such as `onExpand`.

**Desktop (please complete the following information):**
 - OS: `macOS`
 - Browser: `chrome`
 - Version: `114.0.5735.133 (Official Build) (arm64)`

**Comment by dgreene1** [comment]
@brettinternet We’re open to PRs if you’d like to submit a fix.
