### ISSUE TITLE
updating selectedIds fires onNodeSelect

### ISSUE THREAD

**Issue by sandro768** [dgreene1/react-accessible-treeview#131]
**Describe the bug**
docs of onNodeSelect says **onNodeSelect called when a node was manually selected/deselected** but
updating **selectedIds**  array fires onNodeSelect

I've created a sandbox as an example. button click fires **react-router-dom's** **useNavigate** hook, after the navigation **selectedIds** will be updated (as its state depends on query params) therefor **onNodeSelect**  will be fired even though I haven't selected/deselected anything manually

**To Reproduce**
1. Visit [sandbox](https://codesandbox.io/s/elegant-haze-pmpsq8?file=/src/styles.css)
2. open the console to observe
3. Enter https://pmpsq8.csb.app/folders/2 in URL of the sandbox
4. Click(expand) Node modules
5. Click button which is at the top of the page
6. you will see that after the navigation onNodeSelect gets fired

**Comment by dgreene1** [comment]
We’re open to a PR for this.
