### ISSUE TITLE
Allow us to override the list component 

### ISSUE THREAD

**Issue by baba43** [dgreene1/react-accessible-treeview#152]
First of all, thank you for the work!

I would like to implement this component in Mantine, for which I would need the ability to override the list component so that I can use a custom component for `<ul>`.

I wonder if this would be feasible?

**Comment by dgreene1** [comment]
I’m not certain but it’s my gut feeling that by allowing that much flexibility we would be removing the ability to ensure that the library remains WCAG compliant. Also, we don’t have the staff to support this feature request. So, you are probably best off forking.
