### ISSUE TITLE
Focus on tree element after reload 

### ISSUE THREAD

**Issue by oPreis-Systecs** [dgreene1/react-accessible-treeview#156]
# Problem description
After executing a context action on a tree element, the focus is lost and the user has to navigate again to the modified location in the tree.

**Example:**
The user clicks on a menu at a tree element, which opens a dialog. The user changes the tree there (add, delete, edit an element). Afterwards the dialog closes and the tree is reloaded. The keyboard focus on the original tree element is lost and the user starts again in the tree above.

**Currently it is not possible for me to manually set the focus in the tree. (Or is it?)**

# Possible solution
It would be helpful to set the focus manually/controlled on a tree element. This way the user comes back to his starting point and can continue there.

**Comment by dgreene1** [comment]
We’d be open to a PR if you want to submit it but I can’t promise it will be merged since there are normal react, jquery, and browser API ways to do this.

**Comment by oPreis-Systecs** [comment]
Yes there are normal ways to set the focus, but not in such a way that the tree accepts it properly. If I set the focus on a tree element and want to navigate from there with the keyboard, the focus starts again at the top of the tree.

**Comment by dgreene1** [comment]
Okay. We’ll review your PR if you’d like to submit one.

**Comment by Ethaan** [comment]
@opreisSys did you manage to solve this? i'm trying to put the keyboard focus on the first element id inside defaultExpandedIds but no luck

**Comment by oPreis-Systecs** [comment]
> @opreisSys did you manage to solve this? i'm trying to put the keyboard focus on the first element id inside defaultExpandedIds but no luck

I currently have no capacity to fix it. But I still need a solution here, because it is an accessibility problem.

**Comment by dgreene1** [comment]
Can you provide documentation that this is an accessibility problem? It appears to be a usability problem.

I’ll reopen the issues so that someone might contribute it. But currently it’s out of scope for my team too.

help wanted.

**Comment by oPreis-Systecs** [comment]
@dgreene1 Thank you for reopening the issue!
From my point of view, it is both an usability and accessibility problem.

1. a blind user navigates in the tree using the keyboard and opens a dialog from there.
2. user is in the dialog and rerenders the tree when closing the dialogue.
3. user loses focus in the tree and has to find the location again.

As I mentioned above, unfortunately it does not help to set the focus with browser API methods, as the tree does not accept it and navigates from there back to the top of the tree.

As soon as I have found the relevant place in the accessibility guidelines, I will get back to you.

**Comment by yhy-1** [comment]
[opreisSys](https://github.com/opreisSys) Can you try with the new focus props?  [V2.9.0](https://github.com/dgreene1/react-accessible-treeview/releases/tag/v2.9.0)

**Comment by oPreis-Systecs** [comment]
> [opreisSys](https://github.com/opreisSys) Can you try with the new focus props? [V2.9.0](https://github.com/dgreene1/react-accessible-treeview/releases/tag/v2.9.0)

Oh super! This property solved my problem. Thank you.
