### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'id')" with Asynchronous Loading after Re-rendering compoent

### ISSUE THREAD

**Issue by ui-jenny-hong** [dgreene1/react-accessible-treeview#161]
**Describe the bug**
I encountered an issue when using asynchronous loading with react-accessible-treeview. After initially loading child data by clicking on a parent node, if I hide the component and then display it again, clicking on the same parent node to fetch child data results in an error: "Cannot read properties of undefined (reading 'id')".

**Example Code:**

Here is a [CodeSandbox link](https://codesandbox.io/s/react-accessible-treeview-forked-dj3rnw?file=/src/App.js:242-246) that reproduces the issue.

**To Reproduce**
1. Load the provided example.
2. Click on a parent node to trigger onLoadData and fetch child data.
3. Click on the "display" button to hide the <Tree /> component.
4. Click the "display" button again to show the <Tree /> component.
5. Click on the same parent node as in step 2.
6. The error "Cannot read properties of undefined (reading 'id')" is thrown.

**Expected behavior**
After re-displaying the <Tree /> component, I should be able to click on any parent node and load child data without any errors.

**Screenshots**
<img width="1583" alt="截圖 2023-10-29 下午9 42 28" src="https://github.com/dgreene1/react-accessible-treeview/assets/121414200/ed6a2d35-42d9-4a50-a34c-962cd51ae0eb">

**Comment by dgreene1** [comment]
@ui-jenny-hong, I can’t tell from the example if the issue is in the library or in the calling code. But if you’re willing to make a PR, we’ll accept it. We’d want to make sure that the bug can be reproduced in our unit testing code.
