### ISSUE TITLE
Question: Open new node/closing the other nodes

### ISSUE THREAD

**Issue by techogdev** [dgreene1/react-accessible-treeview#163]
Is it possible to close all open nodes in the tree when I open another node?

**Comment by dgreene1** [comment]
How did you bypass the form that requires you to either pick a feature request or a bug report?

Please fill out the issue properly in a new issue and then close this one.

![IMG_7774](https://github.com/dgreene1/react-accessible-treeview/assets/14020024/a6497770-60cf-4620-9f1c-5f592a7673d5)

**Comment by techogdev** [comment]
I have opened a feature request.
