### ISSUE TITLE
How do add classes to the leafListItem (li element)

### ISSUE THREAD

**Issue by davecarlson** [dgreene1/react-accessible-treeview#175]
**Describe the bug**
Cannot style at the <li> level

**Code That Causes The Issue**
Missing option

**To Reproduce**
Create a default TreeView

**Expected behavior**
prop to liClassName

Would it be possible to expose a prop that allows us to inject a classname into each of the <li> components ?
Rational - we use tailwind for styling, and want to be able to alernate the colours of the rows. At the moment we cannot do this without writing raw css on the .tree-branch-wrapper , as the nodeRender is one level down the tree, so nth-child(odd), even etc will not work as there's only one node at that level:

```
<ul
  class="tree"
  role="tree"
  aria-multiselectable="false"
  aria-label="location treer"
>
  <li
    role="treeitem"
    aria-expanded="true"
    aria-setsize="2"
    aria-posinset="1"
    aria-level="1"
    aria-disabled="false"
    tabindex="0"
    class="tree-branch-wrapper"
  >
    <div
      class="tree-node tree-node--expanded tree-node__branch"
      style="padding-left: 0px"
    >
    Node
</div>
</li>
</ul>

**Comment by dgreene1** [comment]
We’re open to a PR, but our core team doesn’t have this need so we wouldn’t be writing the PR ourselves to due internal company priority.
