### ISSUE TITLE
How about virtualization?

### ISSUE THREAD

**Issue by sdancer75** [dgreene1/react-accessible-treeview#177]
**Describe the solution you'd like**
Can this module support thousands of items without the async loading? Is the performance acceptable?

**What value does this proposed solution bring to users?**
A TreeItem viewer that supports huge amounts of data

**Describe alternatives you've considered**
Virtualization

**Comment by KrishEnacton** [comment]
I have same question. I am have large amount of data and it is freezing badly when I select or deselect the node

**Comment by dgreene1** [comment]
Unless someone can submit a PR for this, it seems outside of the scope of what I can support.

For now, I recommend considering a different component, or forking this one, or using filtering above component to reduce the number.

**Comment by sdancer75** [comment]
Currently, I created my own TreeItem component to support virtualization.
