### ISSUE TITLE
How do I get the complete path of a file on Select ?

### ISSUE THREAD

**Issue by hosenur** [dgreene1/react-accessible-treeview#179]
Lets take for example I have src/apps/App.tsx, when I select that,  how do I get it complete path?

**Comment by dgreene1** [comment]
I’m sorry, but as our issue intake process communicates, we do not have staff to support questions. The best place for a question like this (that could be for any library, not just our tree library) is StackOveflow.

![IMG_9767](https://github.com/dgreene1/react-accessible-treeview/assets/14020024/71ace9cd-3672-4cee-88c0-da1ed6b2ea6d)
