### ISSUE TITLE
Pressing command + H causes infinite spin

### ISSUE THREAD

**Issue by bnovc** [dgreene1/react-accessible-treeview#182]
**Describe the bug**
With a tree view visible, if you press command + H (on a Mac, to hide the window), tree view has an infinite loop / freezes the page

It hangs in this code in the treeview, haven't fully followed it. 100% reproducing for me on my tree, but I don't see it on the examples. I don't have any key handling code, so I assume this is related to the large size of my tree but haven't narrowed down yet.

Is there any way to disable treeview from trying to handle these keys?

                    default:
                        if (1 === e.key.length)
                            for (var R = X(t, b, n); R !== b; )
                                if (null != R) {
                                    if (re(t, R).name[0].toLowerCase() === e.key.toLowerCase()) return void d({ type: j, id: R, lastInteractedWith: b });
                                    R = X(t, R, n);
                                } else R = le(t).children[0];
                        return;

**Comment by dgreene1** [comment]
There isn’t a way to stop it from handling this but if you’d like to submit a PR to have it work better, we’re open to it.

**Comment by bnovc** [comment]
Attempted to work around this by setting onKeyDown handlers above the tree and stopping the events or doing it on document.body, but no success.

Attempted to build this project, but it fails. Will probably have to get that working though since this breaks my browser every time I use the component.

**Comment by dgreene1** [comment]
@bnovc I assure you that the project runs locally since our team is actively developing it. Perhaps you have an old version of Node or NPM?

You can see our node versions that we work on by looking in our github workflow file.

**Comment by bnovc** [comment]
Deleting that code block from the minified version fixed my issue, in case others want a quick fix as well
