### ISSUE TITLE
Wrong group node selection

### ISSUE THREAD

**Issue by urrri-redis** [dgreene1/react-accessible-treeview#189]
**Describe the bug**

Selection of group nodes is different, depends on order of selectedIds

**To Reproduce**
1. Go to [Checkbox with controlled selectedIds](https://dgreene1.github.io/react-accessible-treeview/docs/examples-MultiSelectCheckboxControlled)
2. Write following list of ids `12,13,14,15,8,9,10` to the IDs input and press "Set" button
3. Node "Tea-11" is not selected, though all its children are.
4. Change list of IDs to `8,9,10,12,13,14,15` and press "Set" button.
5. All nodes are selected correctly.

**Expected behavior**
Order of IDs should not change selection behavior.
Group node should be always represent state of its children selection

**Screenshots**
![image](https://github.com/user-attachments/assets/a9a81865-4a03-4b2a-9879-f344f86e88e3)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [126]

**Comment by dgreene1** [comment]
@urrri-redis are you experiencing this in your production application?

I ask because the IDs you set don’t seem like a real use case—like why would someone select everything underneath a branch but not just select the whole branch?

Either way, we’re open to PRs. This is a volunteer maintained open source repo.

**Comment by urrri-redis** [comment]
@dgreene1 
this is absolutely correct way to have selected ids for fully selected branch.
There are 3 ways:
- only leaves
- only parents, if all leave are selected
- both parents and leaves, if all leaves are selected

some trees allow choose the way to get selection ids, some allow to make it custom way, but all of them must understand all 3ways, when receive selection IDs, even if they are mixed
