### ISSUE TITLE
Allow tree node to be an interactive element

### ISSUE THREAD

**Issue by huyenltnguyen** [dgreene1/react-accessible-treeview#198]
Note: this _has to be highly valuable to all users_ to be considered. Our team has limited time to work on anything that isn't an accessibility feature. That means that we don't have lots of time to review other people's PRs either. So please consider that before requesting the feature.

## Describe the solution you'd like

I'm building a UI with tree view, and in my use case, tree nodes can either be plain text or an interactive element (link or button).

Initially my request was just allowing the `name` property to be a React node (it's currently accepting `string` only):

https://github.com/dgreene1/react-accessible-treeview/blob/29e4094e2ae6be759111fdfa5586fc8f081f5fbf/src/TreeView/types.ts#L24-L25

But if I disregard the type check error and render `name` as an `<a>` still, the keydown event of the `<a>` appears to be ignored— focusing on the `<a>` and pressing Enter or Spacebar won't do anything.

Here is the demo: https://stackblitz.com/edit/vitejs-vite-3tstas?file=src%2FApp.tsx&terminal=dev

<details>
  <summary>Code snippet in case that link doesn't work</summary>

  ```tsx
import React from "react";
import TreeView, { flattenTree } from "react-accessible-treeview";

const folder = {
  name: "",
  children: [
    {
      name: "A",
      children: [{ name: "A1" }, { name: "A2" }],
    },
    {
      name: "B",
      metadata: {
        href: "https://github.com/dgreene1/react-accessible-treeview" 
      }
    },
    {
      name: <a href="https://github.com/dgreene1/react-accessible-treeview" target="_blank">C</a>,
    },
  ],
};

const data = flattenTree(folder);

const BasicTreeView = () => (
  <TreeView
    data={data}
    className="basic"
    aria-label="basic example tree"
    nodeRenderer={({ element, getNodeProps, level }) => {
      const href = element.metadata?.href

      return (
        <div {...getNodeProps()} style={{ paddingLeft: 20 * (level - 1) }}>
          {href ? <a href={href} target="_blank">{element.name}</a> : element.name}
        </div>
      )
    }}
  />
);

export default BasicTreeView;
  ```
</details>

In the demo, I have item `B` and `C` both rendered as links (with slightly different method), but pressing Enter or Space doesn't trigger either of them.

---

For comparison:
- Here is a W3 demo: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/
- Here is a Material UI demo: https://stackblitz.com/edit/react-n9rtnz?file=Demo.tsx
  - This link comes from https://github.com/mui/mui-x/issues/13849

## What value does this proposed solution bring to users?

I think the changes would allow the library to be used in more cases.

## Describe alternatives you've considered

This is more of a workaround than an alternative, but I was able to get the element to work by adding an `onKeyDown` event handler to it.

```tsx
const data = {
  // ...
  {
    name: (
	  <a 
	    href="https://github.com/dgreene1/react-accessible-treeview"
        target="_blank"
		onKeyDown={(event) => {
		  if (event.key === 'Enter' || event.key === 'Spacebar') {
		  	window.location.href = "https://github.com/dgreene1/react-accessible-treeview"
		  }
		}}
	  >
		C
	  </a>
  )},
};
```

## Additional context

N/A

**Comment by dgreene1** [comment]
This would break accessibility by introducing too many opportunities to change the way that keyboard behavior that users expect. I don’t love this term, but I believe that it’s accurate to say that your proposal would introduce a “footgun” in that it would be a shape in which the user could easily shoot themselves in the foot by removing the accessibility that we’re working towards. So I’d recommend forking this lib or using another tree library that doesn’t have the same commitment to accessibility that we do and therefore might allow such a proposal.
