### ISSUE TITLE
Expose dispatch

### ISSUE THREAD

**Issue by hegelstad** [dgreene1/react-accessible-treeview#21]
Hi @lissitz, great contribution to the open source community.

I wonder, are you willing to accept PRs to this repo? I want to expose `dispatch` function to onExpand and onSelect in addition to onBlur for which you have already exposed `dispatch`.

The purpose is to be able to code accordion-like functionality, that collapses previously expanded branches when clicking on a new collapsed branch.

**Comment by lissitz** [comment]
Hi hegelstad, feel free to open a PR. That seems like a relatively common use case.

**Comment by dgreene1** [comment]
@hegelstad this issue is stale. Also, I’m the new maintainer and I would prefer to keep internals internal. So I would not accept a PR that exposed the dispatch. Instead consumers should use the existing publicly exposed callback props.
