### ISSUE TITLE
 Selected Tree Item on Focus - no selected item behaviour

### ISSUE THREAD

**Issue by garyb1** [dgreene1/react-accessible-treeview#50]
I have a concern and I would love to know if this is your expected behaviour (see video attached).

In the APG Tree View Design Pattern notes it says:

For a vertically oriented tree:

When a single-select tree receives focus:
If none of the nodes are selected before the tree receives focus, focus is set on the first node.
If a node is selected before the tree receives focus, focus is set on the selected node.

When a tree item receives focus using the keyboard it has a tabindex value of 0. Then every other field is set to tabindex -1. This is using roving tabindex I guess.

If I tab away from the tree view, the currently focused item will have a tabindex of 0. When I tab back into the tree view component that previous item will regain keyboard focus because it still has a tabindex of 0.

But should it? That item is not in a "selected" state. See the video, I did not select the item but it regained focus. Shouldn't item 0 (from default state) regain focus? or is this a behaviour you desire?

https://user-images.githubusercontent.com/12486130/194409294-0a3a3c4c-8407-4661-8643-be231567da2f.mov

**Comment by dgreene1** [comment]
I’m looking forward to a PR for this if you’re interested @garyb1

**Comment by garyb1** [comment]
@dgreene1 I think this probably warrants more of a discussion.

So I reviewed the component and it's following the[ APG directory treeview example](https://www.w3.org/WAI/ARIA/apg/example-index/treeview/treeview-1/treeview-1b.html). I see now why you needed to update each item with tabIndex 0 for roving tabindex to work.

It's different to the approach of the other example [APG example for navigation](https://www.w3.org/WAI/ARIA/apg/example-index/treeview/treeview-navigation.html) where only the selected item gets tabindex 0 and the rest have tabindex -1 and then programmatically receive focus. My use case for this component is very much similar to the navigation examples so I am not sure if this component will solve my problem.

**Comment by dgreene1** [comment]
So we can close this then? Let me know if we should reopen it.
