### ISSUE TITLE
Remove onBlur from examples

### ISSUE THREAD

**Issue by garyb1** [dgreene1/react-accessible-treeview#51]
In some of the examples we have 

```
onBlur={({ treeState, dispatch }) => {
  dispatch({
    type: "DESELECT",
    id: Array.from(treeState.selectedIds)[0],
  });
}}
```

This deselects the selected node when we focus away from the component. It also breaks the focus tabindex issue #48.
I suggest we remove this from all examples/docs.

**Comment by dgreene1** [comment]
I agree that since the actions taken in onBlur are not standard, it’s doing more harm than good at this moment. I merged the PR.
