### ISSUE TITLE
Pass additional data to nodes

### ISSUE THREAD

**Issue by AlexisLeite** [dgreene1/react-accessible-treeview#70]
It would be great to be able to pass an object of properties to the node on its definition, in order to use it in the renderer. Something like this:

```ts
data: [
  name: 'aNode',
  data: {
    ...someProps
  }
}
```

Currently when I use flattenTree, its not possible to pass a different id to get the props from another place and the name is not a good aproach due to there it could be many nodes with the same name. 

Thank you

**Comment by dgreene1** [comment]
Hi @AlexisLeite. I apologize, but it’s not clear to me what your goal is from the code snippet.

Can you provide a typescript interface that shows what changes would happen to the component type?

And if you’d like to make a draft PR that shows the proposed change, you can. But I can’t promise that we’ll accept the PR until we understand the goal. Note: all final PRs require unit testing, storybook examples, and possibly website examples (via docusaurus).

So start with the Typescript interface since that might help us understand if the functionality that you’re asking for already exists.

**Comment by AlexisLeite** [comment]
Thank you for your answer. My goal is to be able to associate some props to each node of the tree. As an example, if each node is the representation of a file in the server, I want to be able to receive the url of that node on the nodeRenderer.

```ts
interface INodeProps {
  url: string
}

const NodeRenderer = (props: INodeRendererProps<INodeProps>) => {
  return <a href={props.element.nodeProps.url}>{props.element.name}</a>
}
```

I am with too much work these days, but I would like to make a PR maybe the next week. I think that this change should not be too difficult to implement, maybe there is a way to achieve this already. Please let me know if that is the case, thank you for your time.

I've made a little example of the behavior I was talking about, this is how I can it work without modifying the library:

```ts
import TreeView, { INode, INodeRendererProps } from 'react-accessible-treeview';
import React from 'react';

type TNode<PropsType = unknown> = INodeRendererProps & {
  nodeProps: PropsType;
};

const NodeRenderer = (props: TNode<{ url: string }>) => {
  return <div {...props.getNodeProps()}>{props.nodeProps.url}</div>;
};

export function useTreeData<
  PropsType extends Record<number, unknown> = Record<number, unknown>,
>(): {
  data: INode[];
  makeNodeRenderer: (
    nodeRenderer: (props: TNode<PropsType>) => React.ReactNode,
  ) => (props: INodeRendererProps) => React.ReactNode;
} {
  const [nodesData] = React.useState<Record<number, PropsType>>({
    1: {
      url: 'helloWorld.com',
    } as unknown as PropsType,
    2: {
      url: 'letsDoTrees.org',
    } as unknown as PropsType,
  });

  return {
    data: [
      { children: [1, 2], id: 0, name: '', parent: null },
      { id: 1, name: 'a', parent: 0, children: [] },
      { id: 2, name: 'b', parent: 0, children: [] },
    ],
    makeNodeRenderer(nodeRenderer) {
      const newNodeRenderer = (props: INodeRendererProps) =>
        nodeRenderer({ ...props, nodeProps: nodesData[props.element.id] });
      return newNodeRenderer;
    },
  };
}

const ComplexTreeTest = () => {
  const { data, makeNodeRenderer } = useTreeData<{ url: string }>();
  return (
        <TreeView
          sx={{ variant: 'layout.common.trees.primary' }}
          data={data}
          nodeRenderer={makeNodeRenderer(NodeRenderer)}
        />
  );
};
export default ComplexTreeTest;

```

**Comment by dgreene1** [comment]
Hello. It’s a busy week so I might not be fully understanding what you’re attempting to do. What makes it harder to understand is that your suggested change is to add a node renderer function but there already is one on the type. So have you tried using the existing node renderer function?

https://dgreene1.github.io/react-accessible-treeview/docs/api#noderenderer

I’m going to close this issue with the assumption that the current node renderer meets your needs. We’ve used it for similar purposes to the one you described. If you find that something is lacking or off with the current node renderer function please reply, and I will reopen this issue.

**Comment by AlexisLeite** [comment]
While it's true that the nodeRenderer function allows you to pass custom props, its type doesn't. I thought it was not possible because the flattenTree method deletes the custom props on each node, but if I make the array without that method, the renderer get the custom props. The only problem now seems to be of types.
