### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Hocdoc** [dgreene1/react-accessible-treeview#77]
Is it possible to publish a new release to NPM?
I would like to use the treeview with react-18.

**Comment by dgreene1** [comment]
@yhy-1 for some reason I thought we already published a version that worked with React 18?

@Hocdoc what error are you seeing?

**Comment by darshiljani** [comment]
@dgreene1 I'm facing the same issue with React 18. I'm getting an error for unresolved dependency on React version while trying to install the package using NPM. The package code on NPM does not show the dependencies updated in the repository (screenshot attached below for reference), which could be the reason for this issue.

![image](https://user-images.githubusercontent.com/68460069/210768116-77340c5c-1569-4c3f-bf93-752e201dd0fa.png)

**Comment by mellis481** [comment]
@dgreene1 Yes, it was done, in #69. We just need to do a release.

@yhy-1 Can you take care of that this week please?

**Comment by Hocdoc** [comment]
> @Hocdoc what error are you seeing?

Sorry for my late reply:

```
npm install react-accessible-treeview

...
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-accessible-treeview@2.3.1
npm ERR! node_modules/react-accessible-treeview
npm ERR!   react-accessible-treeview@"*" from the root project
```

**Comment by zz707** [comment]
Hello, I have the same problem.

**Comment by dgreene1** [comment]
@yhy-1 if there was a new release that resolved this, please reply and close the issue.

**Comment by yhy-1** [comment]
New release in 2.3.2
