### ISSUE TITLE
Type INode should have an additional property to store meta data.

### ISSUE THREAD

**Issue by owaisahmad-dev** [dgreene1/react-accessible-treeview#86]
**Describe the solution you'd like**
I want to pass some metadata to each node whilst creating the checkbox tree data.

```ts
type INode<T> = INode & {
    metadata: T
}
```

**What value does this proposed solution bring to users?**
The users will then be able to customize the outlook of each node, for example, if they want to add a number of children alongside the name they can pass that information to the parent nodes' metadata. Another example would be to be able to add tags, which can show as span elements alongside the element's name.

**Describe alternatives you've considered**
The alternative currently is to pass all this information somehow inside the name string and then parse that information in the nodeRenderer method. But that seems sub-optimal.

**Comment by dgreene1** [comment]
PRs are welcome if you would like to submit the solution. Ofherwise the current solution exists and is described in https://github.com/dgreene1/react-accessible-treeview/issues/82#issuecomment-1412011052 and #70

**Comment by owaisahmad-dev** [comment]
I will work on it this weekend and create a PR then. It would be a valuable modification.

**Comment by dgreene1** [comment]
Released in https://github.com/dgreene1/react-accessible-treeview/releases/tag/v2.6.0
