### ISSUE TITLE
String support for data id

### ISSUE THREAD

**Issue by yildirimbayrakci** [dgreene1/react-accessible-treeview#89]
Is it possible to add support to accept Data id String?

![image](https://user-images.githubusercontent.com/48350512/222498220-86a0380e-b04f-4601-bebf-ce69ad0b128a.png)

Thanks.

**Comment by korompaiistvan** [comment]
this would be especially useful when using the treeview to render nodes that have UUID-s

**Comment by kpustakhod** [comment]
@korompaiistvan, @yildirim2189, the issue fixed in: https://github.com/dgreene1/react-accessible-treeview/pull/99
